services:
  backend:
    image: ghcr.io/shradha-2491/restaurant-sentiment-backend:latest
    restart: unless-stopped

  frontend:
    image: ghcr.io/shradha-2491/restaurant-sentiment-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
